version: '3.3'
services:
  posts:
    build:
      context: ./src/posts
    expose:
      - 5000
    environment:
      - COMMENTS=comments
      - DBCONNECTIONSTRING=mongo
      - DBNAME=db
      - CACHENAME=postscache
    depends_on:
      - mongo
      - postscache
    networks:
      - network
  
  comments:
    build:
      context: ./src/comments
    expose:
      - 5000
    environment:
      - POSTS=posts
      - DBCONNECTIONSTRING=mongo
      - DBNAME=db
      - CACHENAME=commentscache
    depends_on:
      - mongo
      - commentscache
    networks:
      - network
  
  reverseproxy:
    build: 
      context: ./src/reverseproxy
    ports:
      - 5000:5000
    environment:
      - POSTS=posts
      - COMMENTS=comments
    depends_on:
      - posts
      - comments
    networks:
      - network

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=db
    volumes:
      - ./data:/data/db
    expose:
      - 5000
    networks:
      - network
  
  postscache:
    image: redis:latest
    restart: always
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning --maxmemory-policy allkeys-lru
    networks:
      - network

  commentscache:
    image: redis:latest
    restart: always
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning --maxmemory-policy allkeys-lru
    networks:
      - network

networks:
  network: